# https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress
#
# Install
# helm install --name nginx-ingress-gitlab --namespace gitlab -f ./nginx-ingress.values.yaml stable/nginx-ingress
#
# Upgrade
# helm upgrade -f ./nginx-ingress.values.yaml nginx-ingress-gitlab stable/nginx-ingress

controller:
  # number of nginx instances
  replicaCount: 2

  # require the following annotation on Ingress objects
  # kubernetes.io/ingress.class: "gitlab"
  ingressClass: gitlab

  # only watch for Ingress objects in the gitlab namespace
  scope:
    enabled: true
    namespace: gitlab

  # custom nginx configs
  config:
    proxy-connect-timeout: "15"
    proxy-read-timeout: "600"
    proxy-send-timeout: "600"
    hsts-include-subdomains: "false"
    proxy-body-size: "1024m"
    server-name-hash-bucket-size: "256"
    enable-vts-status: "true"

# route ssh traffic to the Gitlab service in the `gitlab` namespace
tcp:
  22: "gitlab/<service-name>:22"
