apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  external_scheme: https
  external_hostname: git.{{ .Values.baseDomain }}
  registry_external_scheme: https
  registry_external_hostname: registry.{{ .Values.baseDomain }}
  postgres_user: gitlab
  postgres_db: gitlab_production
  pages_external_scheme: {{ .Values.pagesExternalScheme }}
  pages_external_domain: {{ .Values.pagesExternalDomain }}
