{{- if .Values.postgresDedicatedStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "postgresql.fullname" . }}-storage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.postgresAccessMode | quote }}
  {{- if .Values.postgresStorageClass }}
  storageClassName: {{ .Values.postgresStorageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "30Gi" .Values.postgresStorageSize }}
{{- end }}
